version: '2'
services:
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'queue:1:1,active:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    hostname: redis
    image: redis:6.2-rc2-alpine
    ports:
      - '6379:6379'
    volumes:
      - local-redis-volume:/data:cached
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13-alpine
    volumes:
      - postgresql-volume:/var/lib/postgresql/data:cached
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticketing
  redisinsight:
    hostname: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - local-redisinsight-volume:/db:cached
volumes:
  local-redis-volume:
    external: false
  local-redisinsight-volume:
    external: false
  postgresql-volume:
    external: false
