version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    hostname: redis
    image: redis:6.0.9-alpine
    ports:
      - '6379:6379'
    volumes:
      - local-redis-volume:/data:cached
  redisinsight:
    hostname: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - local-redisinsight-volume:/db:cached
volumes:
  local-redis-volume:
    external: false
  local-redisinsight-volume:
    external: false
