/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WaitingRoom {
        "last_updated": string;
        "position": number;
        "progress": number;
        "refreshQueueData": () => Promise<void>;
        "status_url": string;
        "wait_time": string;
    }
}
declare global {
    interface HTMLWaitingRoomElement extends Components.WaitingRoom, HTMLStencilElement {
    }
    var HTMLWaitingRoomElement: {
        prototype: HTMLWaitingRoomElement;
        new (): HTMLWaitingRoomElement;
    };
    interface HTMLElementTagNameMap {
        "waiting-room": HTMLWaitingRoomElement;
    }
}
declare namespace LocalJSX {
    interface WaitingRoom {
        "last_updated"?: string;
        "position"?: number;
        "progress"?: number;
        "status_url"?: string;
        "wait_time"?: string;
    }
    interface IntrinsicElements {
        "waiting-room": WaitingRoom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "waiting-room": LocalJSX.WaitingRoom & JSXBase.HTMLAttributes<HTMLWaitingRoomElement>;
        }
    }
}
